version: 2

build: &BUILD
  steps:
    - checkout
    - restore_cache:
        keys:
          - v2-dependency-cache-{{ .Environment.CIRCLE_STAGE }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - v2-dependency-cache-{{ .Environment.CIRCLE_STAGE }}-master-{{ checksum "package-lock.json" }}
          - v2-dependency-cache-{{ .Environment.CIRCLE_STAGE }}-{{ .Branch }}-
          - v2-dependency-cache-{{ .Environment.CIRCLE_STAGE }}-master-
          # Fallback to using the latest cache for this version of node if nothing else has worked.
          - v2-dependency-cache-{{ .Environment.CIRCLE_STAGE }}-
          # Don't try to use the cache from a different version of node.
        paths:
          - node_modules
    - run: npm install
    - save_cache:
        key: v2-dependency-cache-{{ .Environment.CIRCLE_STAGE }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
        paths:
          - node_modules
    - run: npm test

jobs:
  boron:
    <<: *BUILD
    working_directory: ~/gtg
    docker:
      - image: circleci/node:6.12
  carbon:
    <<: *BUILD
    working_directory: ~/gtg
    docker:
      - image: circleci/node:8.9
  latest:
    <<: *BUILD
    working_directory: ~/gtg
    docker:
      - image: circleci/node:9.1

workflows:
  version: 2
  ci:
    jobs:
      - boron
      - carbon
      - latest
