version: 2

build: &BUILD
  steps:
    - checkout
    - run: npm install
    - run: npm test
    - run: npm run codecov-report

jobs:
  boron:
    <<: *BUILD
    working_directory: ~/gtg
    docker:
      - image: circleci/node:6.12
  carbon:
    <<: *BUILD
    working_directory: ~/gtg
    docker:
      - image: circleci/node:8.9
  latest:
    <<: *BUILD
    working_directory: ~/gtg
    docker:
      - image: circleci/node:9.1
  stryker:
    working_directory: ~/gtg
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: npm install
      - run: npm run stryker
      - store_artifacts:
          path: packages/generic-type-guard/reports/mutation/html
          destination: stryker-generic-type-guard

workflows:
  version: 2
  ci:
    jobs:
      - carbon
      - boron:
          requires: [ 'carbon' ]
      - latest:
          requires: [ 'carbon' ]
      - stryker:
          requires: [ 'carbon' ]
